kyma-project/runtime-watcher

listener/skr_events_listener.go

**Proposed changes**
Removed logger options from listener setup call

Remove log from listener setup

---

listener/Makefile

**Proposed changes**
Add Makefile to listener codebase.

Add Makefile for pipeline

---

.gitignore
kcp/Makefile
kcp/controllers/suite_test.go
kcp/controllers/watcher_controller.go

- Update Makefile to fix failing pipeline
- Fix lint errors

Fix `pre-main-kyma-watcher-kcp-tests` && `pre-main-kyma-watcher-kcp-lint` errors

---

kcp/Makefile
kcp/api/v1alpha1/groupversion_info.go
kcp/controllers/watcher_controller.go
skr/Makefile

Part of https://github.com/kyma-project/test-infra/issues/5859
Necessary for https://github.com/kyma-project/test-infra/pull/5872

Adapt Makefile for Image build

---

listener/http_test.go
listener/watcher_event.go
listener/watcher_event_test.go

Se the Owner as the NamespacedName for the reconcile Loop

Set the Owner as NamespacedName

---

skr/internal/handler.go

- print out responseBody for failed request

enhance error log

---

listener/pkg/event/watcher_event.go

Remove duplicate request size limiter

---

listener/pkg/event/watcher_event.go
skr/internal/handler.go
skr/internal/handler_test.go
skr/internal/handler_util_test.go

- Extend spec filtering to k8s resources without spec field
https://github.com/kyma-project/lifecycle-manager/issues/521

Extend spec filtering to k8s resources without spec field

---

CODEOWNERS

**Description:**
- Added TW as owners of all `.md` files

Add tws as codeowners

---

listener/.golangci.yaml
listener/Makefile
listener/pkg/event/skr_events_listener.go
runtime-watcher/.golangci.yaml
runtime-watcher/Makefile
runtime-watcher/internal/handler.go
runtime-watcher/internal/handler_util_test.go
runtime-watcher/main.go

Before adding GHA for lint, build, test let's fix the lint issues

Prepare for GitHub actions

---

listener/pkg/event/skr_events_listener.go
listener/pkg/metrics/metrics.go

- Implement metrics for the Listener service
https://github.com/kyma-project/lifecycle-manager/issues/750

Listetener Service Metrics

---

.github/workflows/lint-conventional-prs.yml
runtime-watcher/Dockerfile

- add `refactor` as valid PR title prefix 
- bump go version for build layer

chore: Add PR title prefix

---

.github/workflows/lint-conventional-prs.yml
runtime-watcher/internal/handler.go
runtime-watcher/internal/handler_suite_test.go
runtime-watcher/internal/handler_test.go
runtime-watcher/internal/handler_util_test.go
runtime-watcher/internal/parser/parser.go
runtime-watcher/internal/types.go
runtime-watcher/main.go

- Extract parsing of the request obj itself into internal pkg
- Reduce unneeded complexity since `admissionResponseInfo`'s fields are always the same, message is enough
- Align some errors and log statements

refactor: Extract request parser

---

.github/workflows/pull-listener-pkg.yml
.github/workflows/pull-runtime-watcher.yml
listener/.golangci.yaml
listener/Makefile
listener/pkg/event/http_test.go
listener/pkg/event/skr_events_listener.go
listener/pkg/event/watcher_event_test.go
runtime-watcher/.golangci.yaml
runtime-watcher/Makefile
runtime-watcher/internal/handler.go
runtime-watcher/internal/handler_util_test.go
runtime-watcher/internal/serverconfig/config_test.go
runtime-watcher/main.go

- Upgrade golangci/golangci-lint-action to v4.0.0
- Upgrade golangci-lint version used by make lint target to v1.56.2
- Upgrade golangci-lint version used by GHA lint workflow to v1.56.2

chore: Bump golangci-lint action

---

listener/Dockerfile
listener/go.mod
runtime-watcher/Dockerfile
runtime-watcher/go.mod

Upgrade go version to 1.22.1 in both projects

chore: Upgrade go version to 1.22.1

---

.github/workflows/test-e2e-runtime-watcher.yml

- Stop running tests for post main jobs
Resolves https://github.com/kyma-project/lifecycle-manager/issues/1360

chore: Stop running tests for post main jobs 

---

listener/go.mod
runtime-watcher/go.mod

- bumps the golang version in `go.mod` to match the version in the Dockerfile

chore: Align golang to 1.22.4

---

sec-scanners-config.yaml

- updates config to scan latest semver release

chore: Update protecode config to use version 1.0.0

---

runtime-watcher/tests/e2e/watcher_enqueue_test.go

- Rename watcher CR in E2E test

fix: Rename watcher CR in E2E test

---

docs/api.md

Closes [#1152](https://github.com/kyma-project/lifecycle-manager/issues/1152)

docs: Add API Label Info

---

sec-scanners-config.yaml

Update security scanners config to version 1.1.3
- Update security scanners config

chore: Update security scanners config

---

.github/workflows/build-runtime-watcher.yml

- Fix `build-runtime-watcher` pipeline

fix: Update build-runtime-watcher

---

.github/workflows/build-runtime-watcher.yml

fix: Fix Dockerfile path

---

.github/scripts/release/create_changelog.sh
.github/workflows/create-release.yaml

This script tested in the `test-changelog` branch, you can compare the content [here](https://github.com/kyma-project/runtime-watcher/blob/test-changelog/.github/scripts/release/create_changelog.sh)
The test action https://github.com/kyma-project/runtime-watcher/pull/377/checks

fix: Create changelog

---

.github/workflows/create-release.yaml

- watcher image has been renamed

fix: Image repo name for releases

---

sec-scanners-config.yaml

chore: Update image to be scanned

---

.github/workflows/build-image.yml
.github/workflows/create-release.yaml
.github/workflows/test-e2e-runtime-watcher.yml

https://github.com/kyma-project/lifecycle-manager/issues/1943

chore: Decouple build image from e2e

---

.github/workflows/test-e2e-runtime-watcher.yml

- Provide IMAGE_REPO env var to fix wait for image build action
- partially resolves https://github.com/kyma-project/lifecycle-manager/issues/1943

fix: Provide E2E Workflow action with IMAGE_REPO env var

---

.github/workflows/lint-markdown-links.yml

- use the allow-listed version of markdown-link-check

chore: Update markdown-link-check action

---

sec-scanners-config.yaml

chore: Update runtime-watcher img for code scanner

---

.github/workflows/test-e2e-runtime-watcher.yml

fix: Add modulectl version arg in setup tools step for E2E Github Action

---

sec-scanners-config.yaml

chore: Bump sec-scanners-config to target 1.1.8

---

.github/workflows/test-e2e-runtime-watcher.yml

- Adapts E2E tests to work with the updated setup-test-clusters action.

fix: Adapt to the updated setup-test-cluster action

---

sec-scanners-config.yaml

chore: Bump sec-scanners-config to 1.1.9

---

listener/go.mod
listener/go.sum

- Bump golang.org/x/net to v0.33.0

chore(deps): Bump golang.org/x/net to v0.33.0

---

sec-scanners-config.yaml

chore: Bump sec-scanners-config to 1.1.10

---

listener/Dockerfile
listener/go.mod
runtime-watcher/Dockerfile
runtime-watcher/go.mod

Bump golang version.
**Changes proposed in this pull request:**
- Dockerfile
- go.mod
#2214

chore: Bump golang runtime version

---

runtime-watcher/internal/handler.go

- Update `watcher_failed_kcp_total` metric with the number of failed attempts as well

fix: Update Actual Number of Failed KCP Requests

---

.github/workflows/pull-listener-pkg.yml
.github/workflows/pull-runtime-watcher.yml
listener/.golangci.yaml
listener/Makefile
listener/pkg/event/http_test.go
runtime-watcher/.golangci.yaml
runtime-watcher/Makefile
runtime-watcher/internal/cacertificatehandler/ca_certificate_handler_test.go
runtime-watcher/internal/handler_suite_test.go
runtime-watcher/tests/e2e/e2e_suite_test.go

- Use latest golangci-lint action
- Use latest golangci-lint
- Fix issues

chore: Bump golangci lint and action

---

.github/workflows/create-release.yaml

- adds missing id-token write for create release workflow
- closes https://github.com/kyma-project/lifecycle-manager/issues/2263

chore: Add id-token WRITE to Create Release workflow

---

sec-scanners-config.yaml

- Bump the bdba scanned version to the latest release

chore: Bump scanner version to latest release

---

.github/workflows/pull-listener-pkg.yml
.github/workflows/pull-runtime-watcher.yml
listener/.golangci.yaml
listener/Dockerfile
listener/Makefile
listener/go.mod
runtime-watcher/.golangci.yaml
runtime-watcher/Dockerfile
runtime-watcher/Makefile
runtime-watcher/go.mod
runtime-watcher/internal/handler.go
runtime-watcher/internal/serverconfig/config_test.go

- Bump go version for base image and testing
- Bump golangci-lint to 1.64.7 and fix issues, adapt config 
- Bump golangci-lint action to 6.5.1

chore: Bump go version and golangci-lint with action

---

runtime-watcher/go.mod
runtime-watcher/go.sum

- update the `lifecycle-manager/api` dependency

chore: Update lifecycle-manager/api version

---

runtime-watcher/internal/handler.go
runtime-watcher/internal/handler_test.go
runtime-watcher/internal/serverconfig/config.go

- Addresses a vulnerability entry wrt. no providing the `Strict-Transport-Security` header

fix: Set Strict-Transport-Security header

---

sec-scanners-config.yaml

chore: Bump sec-scanners to 1.1.17

---

runtime-watcher/internal/handler.go
runtime-watcher/internal/serverconfig/config.go

- checkmarx codescan does not recognize the indirection
- just set the header directly anyways its not read from env

chore: Set strict transport header

---

sec-scanners-config.yaml

- Bump sec-scanners-config ver

chore: Add 1.1.18 to bdba scanner

---

sec-scanners-config.yaml

- Add scanned image version to release `v1.1.20`

chore: Bump sec-scanners-config tag

---

sec-scanners-config.yaml

Update sec-scanners config
- Update sec-scanners config to version 1.2.1

chore: Update sec-scanners config
