kyma-project/runtime-watcher

listener/example/main.go
listener/pkg/event/http_test.go
listener/pkg/event/skr_events_listener.go

This PR introduces a verification function which needs to be passed to the listener.
If no verification function is needed, a function which just returns 'nil' can be used instead.
This needs to be introduced to have optional verification for incoming requests in-place. An example would be having a domain-name-pinning verification algorithm before adding the event to the reconciliation queue.
Example:
https://github.com/kyma-project/lifecycle-manager/pull/321
(Please review after reviewing this PR)

Introduce 'verify'-function for listener

---

listener/.golangci.yaml
listener/Makefile
listener/example-mtls/kcp/listener/main.go
listener/pkg/event/http_test.go
listener/pkg/event/skr_events_listener.go
listener/pkg/event/watcher_event_test.go

**Proposed changes**
- Export listener event channel to fix a race condition in the tests
- Refactor parallel tests' design to using an indexed range loop to execute all the test cases and not only the last test case.

Fix listener tests race conditions

---

listener/pkg/event/skr_events_listener.go
listener/pkg/event/watcher_event.go
skr/go.mod
skr/go.sum
skr/internal/handler.go

- Upgrade to latest listener pkg version in skr watcher
- Fix remove `Read Body` in Middleware, otherwise Buffer would be empty, thus event cannot be unmarshaled. It is sufficient to just check size
- Include more details in error logs

Fix MiddleWare Body Bug + Small improvements

---

skr/internal/handler.go

Use `watcherEvent` instead of `postbody` in log and error messages.
Why?
`postbody` is a JSON encoded byte string. `watcherevent` is in human readable format

Include Postbody in log  msg

---

.github/pull-request-template.md
.github/workflows/pull-listener-pkg.yml
.github/workflows/pull-runtime-watcher.yml
runtime-watcher/Makefile

Changes:
* Add a PR template
* Add two workflows for lint, build, test
* for listener pkg
* for runtime-watcher
* Fix make build target
Both workflows have been verified on my fork: https://github.com/lindnerby/runtime-watcher/actions PTAL

Add GHA workflows

---

listener/go.mod
listener/go.sum

Upgrade `golang.org/x/text` version to `v0.7.0` because of [CVE-2022-32149](https://www.cve.org/CVERecord?id=CVE-2022-32149)
I upgrade the version to `v0.7.0` because this is the one used in the `runtime-watcher` module.
- Upgrade `golang.org/x/text` to `v0.7.0`
- `go mod tidy`

chore: Upgade golang.org/x/text

---

runtime-watcher/internal/handler.go
runtime-watcher/internal/handler_suite_test.go
runtime-watcher/internal/serverconfig/config.go
runtime-watcher/internal/serverconfig/config_test.go
runtime-watcher/internal/tlstest/certificate_provider.go
runtime-watcher/main.go

- Remove TLS_CALLBACK env variable (default behaviour is TLS now)
- Enhance Env Test with mTLS setup
Closes #129

feat: Make TLS Mandatory for Runtime Watcher

---

runtime-watcher/Dockerfile
runtime-watcher/Makefile
runtime-watcher/main.go

As part of https://github.com/kyma-project/runtime-watcher/issues/134, every released watcher binary should have an explicit version that corresponds to git commit hash.
- log the version at watcher startup
- provide a new flag `-version` that prints the version and exits
- extend the Makefile to build the binary with an explicit version
- extend the Dockerfile to build the docker image with an explicit version
#134

Add explicit watcher version

---

.github/workflows/create-release.yaml
README.md
docs/how_to_release.md
runtime-watcher/scripts/release/create_changelog.sh
runtime-watcher/scripts/release/create_draft_release.sh
runtime-watcher/scripts/release/get_last_release.sh
runtime-watcher/scripts/release/get_release_by_tag.sh
runtime-watcher/scripts/release/publish_release.sh
runtime-watcher/scripts/release/wait_for_image.sh

Add release workflow to the project.
- Adds release workflow to the project
- Adds a document  describing steps to use the new release workflow
#134

feat: Add release workflow

---

listener/Dockerfile
listener/go.mod
runtime-watcher/Dockerfile
runtime-watcher/go.mod

- replacement for https://github.com/kyma-project/runtime-watcher/pull/245 and https://github.com/kyma-project/runtime-watcher/pull/244 bumping the version in dockerfile and go.mod file at the same time

chore: bump golang from `1.22.1` to `1.22.2`

---

listener/go.mod
runtime-watcher/go.mod

Bumps go version in `go.mod` to 1.22.6. This resolves e2e test errors as in https://github.com/kyma-project/runtime-watcher/pull/342 (tested via https://github.com/kyma-project/runtime-watcher/pull/343)
Dockerfiles already use `FROM golang:1.22.6-alpine as builder`

chore: Bump go version to 1.22.6

---

listener/go.mod
listener/go.sum
runtime-watcher/go.mod
runtime-watcher/go.sum

Supersedes
- https://github.com/kyma-project/runtime-watcher/pull/346
- https://github.com/kyma-project/runtime-watcher/pull/345

chore: Bump prometheus/client-golang to 1.20.1

---

listener/go.mod
listener/go.sum
runtime-watcher/go.mod
runtime-watcher/go.sum

Supersedes:
- https://github.com/kyma-project/runtime-watcher/pull/350
- https://github.com/kyma-project/runtime-watcher/pull/349

chore: Bump prometheus/client-golang to 1.20.2

---

.github/workflows/build-runtime-watcher.yml

This PR aims to make this runtime-watcher repository use GitHub Actions for building images, dropping dependency on Prow Jobs for image builds.
**Related Issues**
- Resolves a part of [this issue](https://github.com/kyma-project/lifecycle-manager/issues/1811)
- Implementation in support of [this issue](https://github.com/kyma-project/lifecycle-manager/issues/1811)

feat: Add GitHub Action Workflow for Runtime Watcher Image Build

---

.github/workflows/build-image.yml
.github/workflows/test-e2e-runtime-watcher.yml

Although `workflow_run` can trigger e2e workflow, it's not referenced by PR, which make e2e tests impossible test based on PR.  
This PR refactored workflow dependencies by using build image in e2e workflow.

fix: Make e2e reuse build image workflow

---

listener/Dockerfile
listener/go.mod
runtime-watcher/Dockerfile
runtime-watcher/go.mod

- Bump go version to latest 1.23.2 for listener and runtime-watcher components

chore: Bump go versions to 1.23.2

---

runtime-watcher/go.mod
runtime-watcher/go.sum

- Bump lifecycle-manager api dependency

chore: Bump lifecycle-manager dependency in runtime-watcher

---

sec-scanners-config.yaml

chore: Bump sec-scanners config

---

.github/workflows/create-release.yaml

- This is a hotfix for the "Create Release" workflow. It needs the contents: write permission to create a tag on the repository.
- closes: https://github.com/kyma-project/lifecycle-manager/issues/2263

chore: Add "contents: write" Permission to Create Release Workflow

---

.github/dependabot.yml

- Remove setting of label `docker` in dependabot PRs
- The label does not exist in our repos and results in dependabot comment on dependabot PRs
- The label is not needed 

chore: Remove unnecessary dependabot label

---

sec-scanners-config.yaml

- Bump runtime-watcher to 1.1.16 in security scanners config

chore: Bump runtime-watcher to 1.1.16 in security scanners config

---

runtime-watcher/internal/handler.go
runtime-watcher/internal/handler_test.go

- adds `Content-Security-Policy` header to fix `kyma/security-scans-modular/issues/135834`
- value is set to `default-src 'self'` to enforce that only content from our host itself can be fetched
- we do not have a requirement to load other content like scripts, images, styles, etc. anyway

chore: Add Content-Security-Policy header

---

runtime-watcher/main.go

- Admission Webhook only accepts TLS 1.3 connections
Closes #538

feat: Allow only TLS 1.3 for Admission Webhook

---

runtime-watcher/go.mod
runtime-watcher/go.sum

- Update lifecycle-manager/api version to the [1.3.12](https://github.com/kyma-project/lifecycle-manager/releases/tag/1.3.12)

chore: Bump lifecycle-manager/api version

---

.github/actions/configuration/action.yml
.github/workflows/pull-listener-pkg.yml
.github/workflows/pull-runtime-watcher.yml
Makefile
listener/.golangci.yaml
listener/Makefile
listener/pkg/event/skr_events_listener.go
runtime-watcher/.golangci.yaml
runtime-watcher/Makefile
runtime-watcher/internal/cacertificatehandler/ca_certificate_handler_test.go
runtime-watcher/internal/handler.go
runtime-watcher/internal/handler_util_test.go
runtime-watcher/internal/requestparser/parser.go
runtime-watcher/internal/serverconfig/config.go
runtime-watcher/internal/types.go
runtime-watcher/tests/e2e/e2e_after_test.go
runtime-watcher/tests/e2e/e2e_before_test.go
runtime-watcher/tests/e2e/utils/logassert.go
runtime-watcher/tests/e2e/utils/metrics.go
runtime-watcher/tests/e2e/utils/utils.go
runtime-watcher/tests/e2e/watcher_enqueue_test.go
versions.yaml

- Add versions.yaml similar to lifecycle-manager to read linter version and envtests versions from
- Remaining tooling versions are already read from lifecycle-manager repo for E2E tests: https://github.com/kyma-project/runtime-watcher/blob/2f4e759e706f60b8dea27674699176cde980c729/.github/workflows/test-e2e-runtime-watcher.yml#L53
- Also bump the linter version to: `2.3.1` (with excluded new linter, that does not bring improvements over the old version)
- Add Makefile for root to call both `listener` and `runtime-watcher` lint targets with:
`make lint-all`

chore: Read lint and envtest from version file
